# Generated by Django 5.0 on 2025-02-10 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BBTripLog',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('trip_timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('trip_date', models.DateField(blank=True, db_index=True, null=True)),
                ('trip_start_latitude', models.DecimalField(decimal_places=6, default=None, max_digits=9)),
                ('trip_start_longitude', models.DecimalField(decimal_places=6, default=None, max_digits=9)),
                ('trip_lake', models.CharField(blank=True, max_length=100, null=True)),
                ('weather_forecast_description', models.CharField(blank=True, max_length=255, null=True)),
                ('weather_forecast_temperature', models.FloatField(default=None)),
                ('weather_forecast_pressure', models.FloatField(default=None)),
                ('weather_measured_home_temperature', models.FloatField(default=None)),
                ('weather_measured_home_pressure', models.FloatField(default=None)),
                ('trip_time_prep_starts', models.DateTimeField(blank=True, null=True)),
                ('trip_time_left_house', models.DateTimeField(blank=True, null=True)),
                ('trip_time_at_ramp', models.DateTimeField(blank=True, null=True)),
                ('trip_coordinates_ramp_latitude', models.DecimalField(decimal_places=6, default=None, max_digits=9)),
                ('trip_coordinates_ramp_longitude', models.DecimalField(decimal_places=6, default=None, max_digits=9)),
                ('weather_measured_ramp_temperature', models.FloatField(default=None)),
                ('weather_measured_ramp_pressure', models.FloatField(default=None)),
                ('trip_time_in_water', models.DateTimeField(blank=True, null=True)),
                ('trip_time_fishing_begins', models.DateTimeField(blank=True, null=True)),
                ('trip_time_return_to_ramp', models.DateTimeField(blank=True, null=True)),
                ('trip_time_boat_on_trailer', models.DateTimeField(blank=True, null=True)),
                ('trip_time_leave_ramp', models.DateTimeField(blank=True, null=True)),
                ('trip_time_return_home', models.DateTimeField(blank=True, null=True)),
                ('trip_time_cleanup_at_home_complete', models.DateTimeField(blank=True, null=True)),
                ('trip_time_pull_away_ramp', models.DateTimeField(blank=True, null=True)),
                ('trip_time_prep_done_to_go_home', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
