# Generated by Django 5.0 on 2025-02-10 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boatbrain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBOnWaterLog',
            fields=[
                ('onwater_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('onwater_timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('onwater_date', models.DateField(blank=True, db_index=True, null=True)),
                ('onwater_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('onwater_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('onwater_event_entry', models.TextField(blank=True, null=True)),
                ('onwater_batteryone_voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('onwater_batterytwo_voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('onwater_batterythree_voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('onwater_air_temp', models.FloatField(blank=True, null=True)),
                ('onwater_air_press', models.FloatField(blank=True, null=True)),
                ('trip_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boatbrain.bbtriplog')),
            ],
            options={
                'db_table': 'bb_onwater_log',
                'indexes': [models.Index(fields=['onwater_date'], name='bb_onwater__onwater_4d901b_idx'), models.Index(fields=['onwater_timestamp'], name='bb_onwater__onwater_0cc15b_idx')],
            },
        ),
    ]
