# Generated by Django 5.0 on 2025-02-10 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boatbrain', '0002_bbonwaterlog'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bbtriplog',
            table='bb_trip_log',
        ),
    ]
