# Generated by Django 5.0 on 2025-02-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boatbrain', '0003_alter_bbtriplog_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbtriplog',
            name='trip_coordinates_ramp_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='bbtriplog',
            name='trip_coordinates_ramp_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='bbtriplog',
            name='trip_start_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='bbtriplog',
            name='trip_start_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='bbtriplog',
            name='weather_forecast_pressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bbtriplog',
            name='weather_forecast_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bbtriplog',
            name='weather_measured_home_pressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bbtriplog',
            name='weather_measured_home_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bbtriplog',
            name='weather_measured_ramp_pressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bbtriplog',
            name='weather_measured_ramp_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
