# Generated by Django 5.0 on 2025-02-15 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boatbrain', '0004_alter_bbtriplog_trip_coordinates_ramp_latitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bbtriplog',
            options={'ordering': ['trip_id']},
        ),
    ]
