# Generated by Django 5.0 on 2025-02-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boatbrain', '0005_alter_bbtriplog_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('log_level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('DEBUG', 'Debug')], max_length=10)),
                ('source_file', models.CharField(blank=True, max_length=255, null=True)),
                ('function_name', models.CharField(blank=True, max_length=255, null=True)),
                ('log_message', models.TextField()),
            ],
            options={
                'db_table': 'application_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
