# Generated by Django 5.0 on 2025-02-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boatbrain', '0006_applicationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbtriplog',
            name='trip_type',
            field=models.CharField(choices=[('REAL', 'Real Trip'), ('TEST', 'Test Data')], db_index=True, default='REAL', max_length=10),
        ),
    ]
